### ISSUE TITLE
`PolymorphicProxySerializer` with list views

### ISSUE THREAD

**Issue by Jusstas** [tfranzel/drf-spectacular#910]
**Describe the bug**
Using `PolymorphicProxySerializer` with list views throws an error.

Introduced in 68e2b1b68d5d9157735f0ce9700e36182dd662ba
drf-spectacular 0.23.0 to 0.25.0:
```
. . .
  File "d:\projects\github\drf-spectacular\drf_spectacular\openapi.py", line 1337, in _get_response_for_code
    is_list_serializer_customized(serializer)
  File "d:\projects\github\drf-spectacular\drf_spectacular\plumbing.py", line 105, in is_list_serializer_customized
    and get_class(get_list_serializer(obj)).to_representation  # type: ignore
  File "d:\projects\github\drf-spectacular\drf_spectacular\plumbing.py", line 99, in get_list_serializer
    return force_instance(obj) if is_list_serializer(obj) else get_class(obj)(many=True)
  File "d:\projects\github\drf-spectacular\drf_spectacular\utils.py", line 85, in __new__
    instance = cls.many_init(*args, **kwargs)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\rest_framework\serializers.py", line 143, in many_init
    child_serializer = cls(*args, **kwargs)
TypeError: __init__() missing 3 required positional arguments: 'component_name', 'serializers', and 'resource_type_field_name'
```

drf-spectacular 0.25.0 and the following:
```
. . .
  File "d:\projects\github\drf-spectacular\drf_spectacular\openapi.py", line 1368, in _get_response_for_code
    is_list_serializer_customized(serializer)
  File "d:\projects\github\drf-spectacular\drf_spectacular\plumbing.py", line 122, in is_list_serializer_customized
    and get_class(get_list_serializer(obj)).to_representation  # type: ignore
  File "d:\projects\github\drf-spectacular\drf_spectacular\plumbing.py", line 116, in get_list_serializer
    return force_instance(obj) if is_list_serializer(obj) else get_class(obj)(many=True, context=obj.context)
  File "d:\projects\github\drf-spectacular\drf_spectacular\utils.py", line 85, in __new__
    instance = cls.many_init(*args, **kwargs)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\rest_framework\serializers.py", line 143, in many_init
    child_serializer = cls(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'context'
```

This also affects any custom serializers that have required arguments.

**To Reproduce**
``` Python
class TestSerializer(serializers.Serializer):
    test_field = serializers.CharField()


@extend_schema(
    responses=PolymorphicProxySerializer(
        component_name='test',
        serializers=[TestSerializer],
        resource_type_field_name=None,
    ),
)
class TestViewSet(ListAPIView):
    pass
```

---

I also got an error by passing 4 positional arguments to `PolymorphicProxySerializer` with `many=True`:
``` Python
PolymorphicProxySerializer('test', [TestSerializer], None, many=True)
```
Produces:
```
. . .
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\rest_framework\serializers.py", line 593, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() takes from 1 to 3 positional arguments but 4 were given
```
But this is easily avoided by using all keyworded arguments.

**Comment by tfranzel** [comment]
Interesting! Strange that this hasn't come up earlier, given that the change has been rolled out for a couple of months.

Yes, I can confirm this is a regression introduced in 0.23.0 due to the new `is_list_serializer_customized` feature.

In case you were not aware, you can quickfix this like so:

```python
@extend_schema(
    responses=PolymorphicProxySerializer(
        component_name='test',
        serializers=[TestSerializer],
        resource_type_field_name=None,
        many=True, # <---------
    ),
)
class TestViewSet(ListAPIView):
    pass
```
Which will prevent the wrong initialization by doing it right up front. That should be fine at least for `ListAPIView`.

**Comment by tfranzel** [comment]
Stacktrace 1 and 2 got fixed in `0.26.3` by #1012

We now support `PolymorphicProxySerializer` on Viewsets where it gets implicitly used with `many=True` on `list`

> I also got an error by passing 4 positional arguments to PolymorphicProxySerializer with many=True:

positional arguments without the `many=True` will now work also, but not with `many=True` due to DRF quirks. I think this is acceptable, since the `many` is not needed anymore here.

I'll close this as fixed but feel free to raise this again and we will reopen.
